name: Verify MX Servers
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  netcat25:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          newlist=$(mktemp)
          faillist=$(mktemp)
          for _name in $(<mx_servers.txt);do
            echo "Checking ${_name}"
            (echo | nc -z ${_name} 25 2>/dev/null) && ( echo ${_name} >> ${newlist} ) || ( echo ${_name} >> ${faillist} )
          done
          sort -u ${newlist} > mx_servers.txt
      - name: Create commits
        run: |
          git config user.name 'Pantelis Roditis'
          git config user.email 'proditis@users.noreply.github.com'
          [[ -z $(git status -s) ]] || git commit -am "Modify tracked file during workflow"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          body: Update changelog to reflect release changes
